# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: table widget

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache Conda
      uses: actions/cache@v1
      with:
        path: ~/.conda
        key: ${{ runner.os }}-mconda-${{ hashFiles('**/configuration.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-          
    - name: Set up Conda
      uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: "latest"
    - name: Verify conda version
      shell: bash
      run: conda --version
    - name: Checkout beakerx_tabledisplay repo
      uses: actions/checkout@v2
      with:
        repository: twosigma/beakerx_tabledisplay
        path: beakerx_tabledisplay
    - name: Checkout beakerx_base repo
      uses: actions/checkout@v2
      with:
        repository: twosigma/beakerx_base
        path: beakerx_base
    - name: Checkout beakerx_tests repo
      uses: actions/checkout@v2
      with:
        repository: twosigma/beakerx_tests
        ref: vladimir/tableTest
        path: beakerx_tests
    - name: Update conda package
      shell: bash -l {0}
      run: |
        cd $GITHUB_WORKSPACE/beakerx_tabledisplay
        conda env create -n beakerx -f configuration.yml
    - name: Build BeakerX Base
      shell: bash -l {0}
      run: |
        conda activate beakerx
        cd $GITHUB_WORKSPACE/beakerx_base
        pip install -e .
    - name: Build BeakerX tabledisplay
      shell: bash -l {0}
      run: |
        conda activate beakerx
        cd $GITHUB_WORKSPACE/beakerx_tabledisplay/beakerx_tabledisplay
        pip install -e .
        beakerx_tabledisplay install
    - name: Fonts
      shell: bash
      run: fc-list
    - name: Run e2e tests (Autotranslation kernel)
      shell: bash -l {0}
      run: |
        cd $GITHUB_WORKSPACE/beakerx_tests/autotests
        chmod +x gradlew
        conda activate beakerx
        python ci_tests.py --app=notebook --tst=python.TableAPI*
    - name: Archive screenshot results
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: screenshots
        path: ${{ github.workspace }}/beakerx_tests/autotests/resources/img
    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        report_paths: "**/test-results/test/TEST-*.xml" 
