name: kernel autotranslation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Set up Conda
      uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: "latest"
    - name: Cache Conda
      uses: actions/cache@v1
      with:
        path: ~/.conda
        key: ${{ runner.os }}-mconda-${{ hashFiles('**/configuration.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda- 
    - name: Verify conda version
      shell: bash -l {0}
      run: conda --version
    - name: Checkout beakerx_tests repo
      uses: actions/checkout@v2
      with:
        repository: twosigma/beakerx_tests
        path: beakerx_tests
    - name: Checkout beakerx_kernel_base repo
      uses: actions/checkout@v2
      with:
        repository: twosigma/beakerx_kernel_base
        path: beakerx_kernel_base
    - name: Build BeakerX Kernel Base
      shell: bash -l {0}
      run: |
        cd beakerx_tests/dev_scripts
        ./install_kernels_notebook.sh
