name: windows Groovy kernel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Checkout beakerx_kernel_base repo
      uses: actions/checkout@v2
      with:
        repository: twosigma/beakerx_kernel_base
        ref: vladimir/windows_action
        path: beakerx_kernel_base
    - name: Set Var
      run: |
         echo "::set-env name=TMP::$env:USERPROFILE\AppData\Local\Temp"
         echo "::set-env name=TEMP::$env:USERPROFILE\AppData\Local\Temp"
    - name: Build BeakerX Kernel Base
      run: |
        echo $Env:GITHUB_WORKSPACE
        cd $Env:GITHUB_WORKSPACE\beakerx_kernel_base
        ./gradlew install
        
